<?php
$conf=array(
//基础参数
'isinstall'=>'1',//网站安装状态（0为未安装，1为已安装）
'webmode'=>'1',//网站状态（0为关闭，1为运行）
'welcome'=>'',//网站状态（0为关闭，1为运行）
'showtime'=>'0',//显示执行时间
'iscode'=>'1',//开启验证码（1开启）
'isdel'=>'1',//内容和分类是否直接删除不进入回收站（1开启）
'tianqimark'=>'0',//后台是否显示天气（0关闭,1开启可关闭,2开启）
'bugmark'=>'0',//调试模式
'sitepath'=>'/',//网站总目录例如:/cms/
'adminpath'=>'_admin999/',//网站后台总目录例如:admin_aspcms
'closeinfo'=>'很抱歉，升级维护中！,开通时间另行通知！',//网站状态（0为关闭，1为运行）
'prefix'=>'cms999_',//cookie,session，前缀，建议每个网站设不一样的

//静态缓存
'runmode'=>'0',//网站运行模式（0为动态，1为静态）
'htmldir'=>'zhcn/',//静态生成路径（可为空，建议为a/）
'enhtmldir'=>'zh/',//静态生成路径（可为空，建议为a/）
'iscache'=>'0',//缓存模式（1开启）
'cachetime'=>'1',//单位小时，默认1小时
'siteext'=>'.html',//链接后缀（可以为空或.htm,.html,.php,.jsp）
 
//后台分页设置
'pagesize'=>'50',//默认分页数量
'sortsize'=>'300',//分类折叠数量

//数据库，支持mysql，sqlite，access，推荐使用mysql
'db'=>array(
'type'=>'mysql',//数据库类型
'showsql'=>'0',
'tablepre'=>'zzz_',
//mysql
'host'=>'127.0.0.1',//数据库地址
'port'=>'3308',//数据库端口
'name'=>'webdata',//数据库名
'user'=>'root',//数据库帐号
'password'=>'',//数据库密码
'charset'=>'utf8',
'engine'=>'InnoDB',
//access
'accesspath'=>'',
'accessname'=>'',
//sqlite
'sqlitepath'=>'',
'sqlitename'=>'',
),


//手机网站
'wapmark'=>'0',//手机网站开关
'wapautogo'=>'1',//手机自动跳转
'padautogo'=>'1',//平板自动跳转
'wappath'=>'wap/',

//上传文件目录
'uploadmark'=>'1',//上传设置开关(0为关闭，1为开启)
'uploadpath'=>'upload/',//上传文件根目录
'datefolder'=>'0',//是否创建日期文件夹(0为关闭，1为创建，图片较少建议关闭)
'covermark'=>'1',//同名是否覆盖（0为增加编号上传，1为覆盖,2为略过）

//图片上传限制
'imageext'=>'jpg,jpeg,gif,png',
'imageformat'=>'shijian',//明明规则另外还有{pinyin}拼音,{filename},{yy}{mm}{dd}{hh}{ii}{ss}{rand:6}
'imagemaxsize'=>'10mb',//请注意空间上也会有限制上传大小
'compresswidth'=>'2000',//图片最大宽度
'compressheight'=>'1000',//图片最大高度
'compressquality'=>'90',//图片压缩质量
//附件上传限制
'fileext'=>'pdf,txt,doc,docx,xls,xlsx,zip,rar',
'fileformat'=>'shijian',//附件命名规则
'filemaxsize'=>'10mb',//附件上传限制大小
//视频上传限制
'videoext'=>'mp4,flv',//请注意空间90%以上不允许上传视频，或不支持视频格式
'videoformat'=>'pinyin',
'videomaxsize'=>'200mb',

//缩略图
'smallmark'=>'1',
'about_mode'=>'5','about_width'=>'800','about_height'=>'575','about_quality'=>'100',
'news_mode'=>'5','news_width'=>'800','news_height'=>'575','news_quality'=>'100',
'photo_mode'=>'5','photo_width'=>'800','photo_height'=>'575','photo_quality'=>'100',
'video_mode'=>'5','video_width'=>'400','video_height'=>'500','video_quality'=>'80',
'slide_mode'=>'5','slide_width'=>'500','slide_height'=>'500','slide_quality'=>'80',

//水印参数
'watermark'=>'0',//水印(0,1)
'watertype'=>'0',//水印类型(0为文字，1图片)
'watermarkfont'=>'webcms',//水印文字
'watermarkpic'=>'/images/logo.png',//水印图片
'markpicwidth'=>'100',//宽
'markpicheight'=>'30',//高
'markpicalpha'=>'1',//透明度
'watermarklocation'=>'1',//位置


'textphone'=>'',
'safe_type'=>'0',//白名单类型
'safe_ip'=>'',//白名单
'baiduapiAK'=>'',//百度地图浏览器端，访问应用（AK）
'smallmodel'=>'选择模型',
'brand_mode'=>'5',
'brand_width'=>'500',
'brand_height'=>'500',
'brand_quality'=>'80',
'product_mode'=>'5',
'product_width'=>'500',
'product_height'=>'500',
'product_quality'=>'80',
'job_mode'=>'5',
'job_width'=>'500',
'job_height'=>'500',
'job_quality'=>'80',
'down_mode'=>'5',
'down_width'=>'500',
'down_height'=>'500',
'down_quality'=>'80',
'case_mode'=>'5',
'case_width'=>'500',
'case_height'=>'500',
'case_quality'=>'80',
);